#!/usr/bin/env bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$" | grep -v "mock")

for FILE in ${STAGED_GO_FILES}
do
    gofmt -w -s "${FILE}"
    goimports -w "${FILE}"
    git add "${FILE}"
done
